name = "messenger-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
account_id = "71b0e14ca51602c50c338294d5db1d8c"

[[d1_databases]]
binding = "DB"
database_name = "messenger"
database_id = "a9b891f2-b3ec-4ef8-bc46-e3e04e8bad97"
migrations_dir = "migrations"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]

[vars]
JWT_SECRET = "da977971d374d3b74b71824d78bd9cb1adcd2d3dfe75469741dbed1d829c9285"
ADMIN_USERNAME = "admin"
ALLOWED_ORIGIN = "https://messenger-frontend-dzh.pages.dev"
VAPID_PUBLIC_KEY = "BGdEVCN24foMQ6PxhEt4_UaCNHuGETKZKETrt4dCq3T46mAtILd8stTe75M9u3QqnO1gxvmnNr7dL2JvN0C24z4"
VAPID_PRIVATE_KEY_JWK = '{"kty":"EC","x":"Z0RUI3bh-gxDo_GES3j9RoI0e4YRMpkoROu3h0KrdPg","y":"6mAtILd8stTe75M9u3QqnO1gxvmnNr7dL2JvN0C24z4","crv":"P-256","d":"QG-Ia71l3tI-N8rI_rD2PANoEvs-2NDvVjPLSS3CRNM"}'
VAPID_CONTACT = "mailto:admin@example.com"
